#!/usr/bin/env ts-node

import { readFileSync, existsSync, readdirSync, statSync } from "fs";
import { resolve } from "path";

interface SOPState {
  task_id: string;
  sop: string;
  status: "in_progress" | "completed" | "failed";
  started_at: string;
  completed_at?: string;
  current_step: number;
  steps: Record<string, { status: string; timestamp?: string }>;
  answers: Record<string, Record<string, unknown>>;
}

function getStateDir(): string {
  return resolve(process.cwd(), ".sop", "state");
}

function getOutputDir(): string {
  return resolve(process.cwd(), ".sop", "output");
}

function getExpectedPath(sop: string): string {
  return resolve(process.cwd(), ".claude", "skills", `sop-${sop}`, "expected.yml");
}

function getStepMapPath(): string {
  return resolve(process.cwd(), ".claude", "scripts", "sop-step-map.json");
}

function loadState(sop: string): SOPState | null {
  const dir = getStateDir();
  if (!existsSync(dir)) return null;

  const files = readdirSync(dir)
    .filter((f) => f.startsWith(sop) && f.endsWith(".json"))
    .sort()
    .reverse();

  for (const file of files) {
    try {
      return JSON.parse(readFileSync(resolve(dir, file), "utf-8")) as SOPState;
    } catch { continue; }
  }
  return null;
}

function loadExpected(sop: string): string | null {
  const path = getExpectedPath(sop);
  if (!existsSync(path)) return null;
  return readFileSync(path, "utf-8");
}

function loadStepMap(): Record<string, string[]> | null {
  const path = getStepMapPath();
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf-8"));
}

function listOutputs(sop: string): { path: string; size: number; modified: Date }[] {
  const dir = getOutputDir();
  if (!existsSync(dir)) return [];

  const files = readdirSync(dir)
    .filter((f) => f.startsWith(sop))
    .map((f) => {
      const fullPath = resolve(dir, f);
      const stat = statSync(fullPath);
      return { path: f, size: stat.size, modified: stat.mtime };
    })
    .sort((a, b) => b.modified.getTime() - a.modified.getTime());

  return files;
}

function collectContext(sop: string): void {
  const state = loadState(sop);
  const expected = loadExpected(sop);
  const stepMap = loadStepMap();
  const outputs = listOutputs(sop);
  const skillDir = resolve(process.cwd(), ".claude", "skills", `sop-${sop}`);

  console.log("# SOP Verification Context\n");

  // SOP Info
  console.log("## SOP Info");
  console.log(`- **Name**: ${sop}`);
  console.log(`- **Skill dir**: ${skillDir}`);
  console.log(`- **has expected.yml**: ${expected ? "yes" : "no"}`);
  console.log(`- **has state**: ${state ? "yes" : "no"}`);

  // Step Map
  if (stepMap && stepMap[sop]) {
    console.log(`\n## Expected Step Order (from step-map)`);
    console.log(`\`\`\``);
    stepMap[sop].forEach((step, i) => console.log(`  ${i + 1}. ${step}`));
    console.log(`\`\`\``);
  }

  // State
  if (state) {
    console.log(`\n## Execution State`);
    console.log(`- **Task ID**: ${state.task_id}`);
    console.log(`- **Status**: ${state.status}`);
    console.log(`- **Started**: ${state.started_at}`);
    if (state.completed_at) console.log(`- **Completed**: ${state.completed_at}`);
    console.log(`- **Current Step**: ${state.current_step}`);

    // Step statuses
    console.log(`\n### Step Statuses`);
    console.log(`| Step | Status |`);
    console.log(`|------|--------|`);
    for (const [step, info] of Object.entries(state.steps)) {
      console.log(`| ${step} | ${info.status} |`);
    }

    // Answers
    if (Object.keys(state.answers).length > 0) {
      console.log(`\n### User Answers`);
      console.log(`\`\`\`json`);
      console.log(JSON.stringify(state.answers, null, 2));
      console.log(`\`\`\``);
    }
  } else {
    console.log(`\n## Execution State: *No state file found*`);
  }

  // Expected
  if (expected) {
    console.log(`\n## Expected Definition (expected.yml)`);
    console.log(`\`\`\`yaml`);
    console.log(expected.trim());
    console.log(`\`\`\``);
  } else {
    console.log(`\n## Expected Definition: *No expected.yml found*`);
  }

  // Outputs
  console.log(`\n## Output Files`);
  if (outputs.length === 0) {
    console.log(`*No output files found in .sop/output/*`);
  } else {
    console.log(`| File | Size | Modified |`);
    console.log(`|------|------|----------|`);
    for (const out of outputs) {
      const sizeStr = out.size > 1024
        ? `${(out.size / 1024).toFixed(1)}KB`
        : `${out.size}B`;
      console.log(`| ${out.path} | ${sizeStr} | ${out.modified.toISOString().slice(0, 19)} |`);
    }
  }

  // Skills directory check
  console.log(`\n## Skills Directory`);
  console.log(`- **Path**: ${skillDir}`);
  console.log(`- **Exists**: ${existsSync(skillDir)}`);

  console.log(`\n---`);
  console.log(`*Generated by sop-verify.ts at ${new Date().toISOString()}*`);

  // Summary counts for agent consumption
  if (state && expected) {
    const expectedSteps = expected.match(/^\s+- id:/gm);
    const actualSteps = Object.keys(state.steps);
    const outputCount = outputs.length;
    const stepCount = actualSteps.length;
    const expectedStepCount = expectedSteps ? expectedSteps.length : 0;

    console.log(`\n## Quick Stats`);
    console.log(`- **Expected Steps**: ${expectedStepCount}`);
    console.log(`- **Actual Steps**: ${stepCount}`);
    console.log(`- **Output Files**: ${outputCount}`);
    console.log(`- **All Steps Completed**: ${Object.values(state.steps).every(s => s.status === "completed")}`);
  }

  // Anti-pattern detection hints
  console.log(`\n## Anti-pattern Checks (manual)`);
  console.log(`1. **Step compliance**: Compare actual steps vs expected step-map order`);
  console.log(`2. **Output completeness**: Check all required outputs exist`);
  console.log(`3. **State consistency**: Verify completed steps have matching outputs`);
  console.log(`4. **Parameter consistency**: Verify user answers were used in execution`);
}

const args = process.argv.slice(2);
if (args.length === 0) {
  console.log("Usage: ts-node sop-verify.ts <sop-name>");
  console.log("");
  console.log("Example: ts-node sop-verify.ts code-review");
  process.exit(1);
}

const sop = args[0];
collectContext(sop);
